title: Monero.com Guides
description: Monero.com guides and support resources
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/images/Cake Wallet Logo.png"

url: "https://guides.monero.com"

permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "monero.com":
    - "https://monero.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# External navigation links
nav_external_links:
  - title: monero.com
    url: https://monero.com

# Enable or disable heading anchors
heading_anchors: true

# Optional callouts. To use: {: .warning } before paragraph
callouts:
  warning:
    title: Warning
    color: red
  friendly:
    color: blue

# Footer content
footer_content: "Copyright &copy; Cake Labs LLC using Just the Docs"
back_to_top: true # Back to top link
back_to_top_text: "Back to top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cake-tech/monerocom-guides" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false